### ISSUE TITLE
Не-qwerty раскладки

### ISSUE THREAD

**Issue by balsoft** [danakt/pshe#1]
Хардкодить layout -- это преступление против адекватных раскладок.

**Comment by danakt** [comment]
@balsoft весомо. Что предлагаете?

**Comment by balsoft** [comment]
Если делать костыли, то можно тащить раскладку из `XKB_DEFAULT_LAYOUT` и написать маппинги для популярных раскладок. Если велосипеды -- то https://www.npmjs.com/package/convert-layout или https://www.npmjs.com/package/lang-layout-switcher (не проверял, есть ли в этих библиотеках поддержка дворака).

**Comment by danakt** [comment]
@balsoft на счёт `XKB_DEFAULT_LAYOUT` увы ничего не могу сказать. `convert-layout`, увы, не предусматривает раскладку macos, а `lang-layout-switcher` вообще будет сомнительной зависимостью. Оба решения громоздкие и будут лишними, учитывая что мне кода нужно на несколько строк.

И не стоит забывать что этот проект скорее просто рофл, есть более полезные и жизнеспособные инструменты, например [thefuck](https://github.com/nvbn/thefuck)
