### ISSUE TITLE
Only пше is supported

### ISSUE THREAD

**Issue by p-hash** [danakt/pshe#6]
Hello guys

I believe it is easy to modify the code to support any command, and not just `пше`. 

I am not good at js, but usually command itself comes in an `argv[0]` and can be transcribed using same rules and can be found in `$PATH` for correct binary.

It will be tricky to set up a trigger for this, but `command-not-found` handler seems to be a good place to put it. Here is an example for bash
https://www.linuxjournal.com/content/bash-command-not-found

**Comment by danakt** [comment]
Hello! The concept of the tool is only in support of `пше` command. You can use a more convenient tool: https://github.com/nvbn/thefuck
